#!/usr/bin/env bash

if ! [ -f .env ]; 
then 
  echo "[!] First configure your testenv by creating a .env file"
  exit
fi

source .env

if ! command -v ganache-cli &> /dev/null
then
  echo "[!] \`ganache-cli\` was not found in your \$PATH"
  exit
fi

ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul \
  --fork "$PROVIDER" \
  --mnemonic "$MNEMONIC" \
  --unlock "$ADDRESS"